producer:
  build: producer
  ports:
    - "80"
  volumes:
    - ./producer:/src
aggregator:
  build: aggregator
  ports:
    - "80"
  links:
    - producer
  volumes:
    - ./aggregator:/src
webclient:
  build: webclient
  ports:
    - "80"
  links:
    - aggregator
  volumes:
    - ./webclient:/src
